services:
  app:
    image: bookstore-app
    container_name: bookstore-app-container
    restart: unless-stopped
    environment:
      - DB_URL=jdbc:postgresql://db:5432/bookstore
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:17.5
    container_name: postgres-sql-spring-app
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bookstore
      PGDATA: /data/postgres
    volumes:
      - "D:/docker-data/bookstore-postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
volumes:
  postgres:

networks:
  default:
    name: bookstore_default_network